---
#
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory
#

# we need to collect facts from all hosts we reference
# https://github.com/ansible/ansible/issues/9260
# we skip switches/oobservers because they normally don't
# have python installed.

- hosts: all
  become: yes
  tasks: []

# role for nagios clients via NRPE
- hosts: all
  become: yes
  roles:
    #-  nagios-client 
    -  role: nagios-client 
  #  - { role: firewall_client, when: manage_firewall_client }

# role for nagios server
- hosts: nagios
  become: yes
  roles:
    -  role: nagios 
#    - { role: firewall, when: manage_firewall }
#    - { role: instructions }
